```{r}
library(chillR)
library(tidyverse)
```
```{r}
Dehesa_temps <- read.csv("D:/DatenVehlken/R/Projects/Chill_R/Dehesa_temps.csv")
```



```{r}
RCPs <- c("rcp45",
          "rcp85")
Times <- c(2050,
           2085)

for(RCP in RCPs)
  for(Time in Times)
  {start_year <- Time - 15
  end_year <- Time + 15
  clim_scen <-
    getClimateWizardData(
      c(longitude = -6.2333,
        latitude = 37.8667),
      RCP,
      start_year,
      end_year,
      temperature_generation_scenarios = TRUE,
      baseline =c(1975, 2005),
      metric = "monthly_min_max_temps",
      GCMs = "all")
  save_temperature_scenarios(clim_scen,
                             "data/ClimateWizard",
                             paste0("Dehesa_futures_",Time,"_",RCP))}
```

```{r}
scenario_1990 <- Dehesa_temps %>%
  temperature_scenario_from_records(1990)

scenario_1996 <- Dehesa_temps %>%
  temperature_scenario_from_records(1996)

adjustment_scenario <-
  temperature_scenario_baseline_adjustment(scenario_1996,
                                           scenario_1990)

print(adjustment_scenario)
```
```{r}
RCPs <- c("rcp45",
          "rcp85")
Times <- c(2050,
           2085)
```

```{r}
for(RCP in RCPs)
  for(Time in Times)
  {
    clim_scen <- load_ClimateWizard_scenarios(
      "data/climateWizard",
      paste0("Dehesa_futures_",
             Time,
             "_",
             RCP))
    
    clim_scen_adjusted <-
      temperature_scenario_baseline_adjustment(
        baseline_temperature_scenario = adjustment_scenario,
        temperature_scenario = clim_scen)
    
    Temps <- temperature_generation(
      weather = Dehesa_temps, 
      years = c(1973,
                2019),
      sim_years = c(2001,
                    2101),
      temperature_scenario = clim_scen_adjusted)
    
    save_temperature_scenarios(
      Temps,
      "data/Weather_ClimateWizard",
      paste0("Dehesa_",
             Time,
             "_",
             RCP))
  }
```

```{r}
all_past_scenarios <- temperature_scenario_from_records(
  weather = Dehesa_temps,
  year = c(1980,
           1990,
           2000,
           2010))

adjusted_scenarios <- temperature_scenario_baseline_adjustment(
  baseline = scenario_1996,
  temperature_scenario = all_past_scenarios)

all_past_scenario_temps <- temperature_generation(
  weather = Dehesa_temps,
  years = c(1973,
            2019),
  sim_years = c(2001,
                2101),
  temperature_scenario = adjusted_scenarios)

save_temperature_scenarios(
  all_past_scenario_temps,
  "data/Weather_ClimateWizard",
  "Dehesa_historic")
```


```{r}
frost_model <- function(x)
  step_model(x,
             data.frame(
               lower=c(-1000,0),
               upper=c(0,1000),
               weight=c(1,0)))

models <- list(Chill_Portions = Dynamic_Model,
               GDH = GDH,
               Frost_H = frost_model)
```


```{r}
Temps <- load_temperature_scenarios("data/Weather_ClimateWizard",
                                    "Dehesa_historic")

chill_past_scenarios <-
  Temps %>%
  tempResponse_daily_list(
    latitude = 37.8667,
    Start_JDay = 305,
    End_JDay = 59,
    models = models,
    misstolerance = 10)

chill_observed <- 
  Dehesa_temps %>%
  tempResponse_daily_list(
    latitude = 37.8667,
    Start_JDay = 305,
    End_JDay = 59,
    models = models,
    misstolerance = 10)

save_temperature_scenarios(chill_past_scenarios,
                           "data/chill_ClimateWizard",
                           "Dehesa_historic")
save_temperature_scenarios(chill_observed,
                           "data/chill_ClimateWizard",
                           "Dehesa_observed")
```

```{r}
for(RCP in RCPs)
  for(Time in Times)
    {
    Temps <- load_temperature_scenarios(
      "data/Weather_ClimateWizard",
      paste0("Dehesa_",
             Time,
             "_",
             RCP))
    chill <- Temps %>% 
      tempResponse_daily_list(
        latitude = 37.8667,
        Start_JDay = 305,
        End_JDay = 59,
        models = models,
        misstolerance = 10)
    save_temperature_scenarios(
      chill,
      "data/chill_ClimateWizard",
      paste0("Dehesa_",
             Time,
             "_",
             RCP))
}
```
```{r}
chill_past_scenarios <- load_temperature_scenarios(
  "data/chill_ClimateWizard",
  "Dehesa_historic")
chill_observed <- load_temperature_scenarios(
  "data/chill_ClimateWizard",
  "Dehesa_observed")

chills <- make_climate_scenario(
  chill_past_scenarios,
  caption = "Historic",
  historic_data = chill_observed,
  time_series = TRUE)

plot_climate_scenarios(
  climate_scenario_list = chills,
  metric = "Chill_Portions",
  metric_label = "Chill (Chill Portions)")
```

```{r}
for(RCP in RCPs)
  for(Time in Times)
    {
    chill <- load_temperature_scenarios(
      "data/chill_ClimateWizard",
      paste0("Dehesa_",
             Time,
             "_",
             RCP))
    if(RCP == "rcp45") RCPcaption <- "RCP4.5"
    if(RCP == "rcp85") RCPcaption <- "RCP8.5"
    if(Time == "2050") Time_caption <- "2050"
    if(Time == "2085") Time_caption <- "2085"
    chills <- chill %>% 
      make_climate_scenario(
        caption = c(RCPcaption,
                    Time_caption),
        add_to = chills)
}
```

```{r}
info_chill <-
  plot_climate_scenarios(
    climate_scenario_list = chills,
    metric = "Chill_Portions",
    metric_label = "Chill (Chill Portions)",
    texcex = 1.5)
```

```{r}
info_heat <-
  plot_climate_scenarios(
    climate_scenario_list = chills,
    metric = "GDH",
    metric_label = "Heat (Growing Degree Hours)",
    texcex = 1.5)
```

```{r}
info_frost <- 
  plot_climate_scenarios(  
    climate_scenario_list=chills,
    metric="Frost_H",
    metric_label="Frost hours",
    texcex=1.5)
```

